// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Lab
{
    public int LabId { get; set; }

    public string LabName { get; set; }

    public string Description { get; set; }

    public string LabFileUrl { get; set; }

    public string VideoUrl { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}